#spring.application.name=practice-hibernate

spring:
  application:
    name: practice-hibernate

  datasource:
#    url: jdbc:h2:./appDB
#    username: sa
#    password: sa

    url: jdbc:mysql://localhost:3306/employeeDB
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  h2:
#    console:
#      enabled: true





server:
  port: 8081





