#spring.application.name=practice-hibernate

spring:
  application:
    name: practice-hibernate

  datasource:
    url: jdbc:h2:./appDB
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  h2:
    console:
      enabled: true

server:
  port: 8081





